import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Projects",
  description: "Generated by create next app",
};

export default function NestedLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
        {children}
    </main>
  );
}
